### ISSUE TITLE
extending or providing tests

### ISSUE THREAD

**Issue by mandric** [lusakasa/saka-extension-boilerplate#1]
Hello,  I was thinking to create a similar project or extend this one to include a little bit of functionality and some tests.  So that it's also clear how the testing frameworks would work, I would include an example of how to do at least one sample unit, functional and integration (e2e) test.  Do you think that would be useful?  Is there something else you would change or update about this project?  Have your opinions changed much regarding the toolset?  I'm doing some research before I embark on a browser extension project and am going to create a similar boilerplate.

**Comment by eejdoowad** [comment]
Hi @mandric, this boilerplate is a little dated, and includes NO testing because, at the time I made it, I was more concerned with development speed and had no experience testing web projects. You would be better served starting with another, more recently maintained boilerplate, but there are some lessons and techniques you can apply from this code base.

* Use Webpack to bundle javascript files and have it generate a separate module for your content script, your background page, your popup, your options page, and any other independently executed script.
* Use a system that generates browser-specific manifests from a common configuration and a browser-specific configuration
* Use Travis CI to automatically check for tagged git commits, and if found, build zip files suitable for uploading to the Chrome Web Store / Mozilla Addons Marketplace
* Organize your codebase by feature, not by page.
* Just build something and get it published. Don't stress about perfection. Make it a goal to ship something NOW.

I can't point you toward a specific boilerplate, but you'll find [this article](https://medium.com/information-and-technology/unit-testing-browser-extensions-bdd4e60a4f3d) by Saka codeveloper @pureooze on testing browser extensions useful.

**Comment by mandric** [comment]
Awesome, thank you so much! I will keep you posted on my adventures.

**Comment by pureooze** [comment]
@mandric if you are interested in e2e testing you can sort of achieve this using Cypress: https://github.com/cypress-io/cypress/issues/1965

**Comment by mandric** [comment]
Any thoughts about puppeteer?

**Comment by pureooze** [comment]
Unfortunately I dont have any experience with puppeteer so I cant really chime in, but if you do end up using it, I would love to know what its advantages and disadvantages are 😄

**Comment by mandric** [comment]
Making a little progress over here, let me know if it stands the test of reason to you:

https://github.com/mandric/extension-testing-example

No e2e solutions yet.  I avoided Jest because I want to actually test in the browser, I think Jest makes sense for DOM testing but not if your are testing the `browser` API (extensions API).
